apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-08-30T09:57:41Z"
  labels:
    run: httpd-pod-2
  name: httpd-pod-2
  namespace: default
  resourceVersion: "34105"
  uid: 4c217eb0-2a0a-4119-8a62-75d1deb1db8f
spec:
  containers:
  - image: httpd
    imagePullPolicy: Always
    name: httpd-pod-2
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-2nk84
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: docker-desktop
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-2nk84
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:57:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:57:41Z"
    message: 'containers with unready status: [httpd-pod-2]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:57:41Z"
    message: 'containers with unready status: [httpd-pod-2]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-08-30T09:57:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - image: httpd-new
    imageID: ""
    lastState: {}
    name: httpd-pod-2
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "httpd-new"
        reason: ImagePullBackOff
  hostIP: 192.168.65.4
  phase: Pending
  podIP: 10.1.0.18
  podIPs:
  - ip: 10.1.0.18
  qosClass: BestEffort
  startTime: "2021-08-30T09:57:41Z"
