apiVersion: v1
kind: Pod
metadata:
  name: httpd-secret-volume-pod
spec:
  containers:
    - name: httpd-secret-volume-pod
      image: httpd
      volumeMounts:
        # name must match the volume name below
        - name: gamesecret-volume
          mountPath: /opt/secret

  volumes:
    - name: gamesecret-volume
      secret: 
        secretName: gamesecret
         