apiVersion: v1
kind: Pod
metadata:
  name: httpd-secret-pod
spec:
  containers:
    - name: httpd-secret-pod
      image: httpd
      envFrom:
        - secretRef:
            name: gamesecret
      env:
        - name: MONGO_HOST
          valueFrom: 
              secretKeyRef:
                name: dbsecret
                key: DB_HOST
        - name: MONGO_USER
          valueFrom: 
              secretKeyRef:
                name: dbsecret
                key: DB_USER
        - name: MONGO_PASS
          valueFrom: 
              secretKeyRef:
                name: dbsecret
                key: DB_PASS
         