apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    type: loadbalancer-replica
spec:
  replicas: 3
  selector: 
    matchLabels:
      type: loadbalancer
  template:
    metadata:
      name: nginx-pod
      labels:
        type: loadbalancer
        country: us
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21.1-alpine
