apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    country: us
spec:
  template:
    metadata:
      name: mongo-pod
      labels:
        type: mongo-db
    spec:
      containers:
        - name: mongo-container
          image: mongo
  replicas: 1
  selector:
    matchLabels:
      type: mongo-db